package springboot.mapper;

import org.apache.ibatis.annotations.Mapper;

import springboot.model.ProductMaintain;
@Mapper
public interface ProductMaintainMapper {
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table product_maintain
	 *
	 * @mbg.generated
	 */
	int deleteByPrimaryKey(String productId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table product_maintain
	 *
	 * @mbg.generated
	 */
	int insert(ProductMaintain record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table product_maintain
	 *
	 * @mbg.generated
	 */
	int insertSelective(ProductMaintain record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table product_maintain
	 *
	 * @mbg.generated
	 */
	ProductMaintain selectByPrimaryKey(String productId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table product_maintain
	 *
	 * @mbg.generated
	 */
	int updateByPrimaryKeySelective(ProductMaintain record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table product_maintain
	 *
	 * @mbg.generated
	 */
	int updateByPrimaryKey(ProductMaintain record);
}