package springboot.model;

import java.io.Serializable;

public class User implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.user_id
     *
     * @mbg.generated
     */
    private String userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.user_name
     *
     * @mbg.generated
     */
    private String userName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.user_paw
     *
     * @mbg.generated
     */
    private String userPaw;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.unionid
     *
     * @mbg.generated
     */
    private String unionid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.org
     *
     * @mbg.generated
     */
    private String org;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.last_org
     *
     * @mbg.generated
     */
    private String lastOrg;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.isManager
     *
     * @mbg.generated
     */
    private String ismanager;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.isRegister
     *
     * @mbg.generated
     */
    private String isregister;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.register_number
     *
     * @mbg.generated
     */
    private String registerNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.register_time
     *
     * @mbg.generated
     */
    private String registerTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.create_time
     *
     * @mbg.generated
     */
    private String createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.update_time
     *
     * @mbg.generated
     */
    private String updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table user
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.user_id
     *
     * @return the value of user.user_id
     *
     * @mbg.generated
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.user_id
     *
     * @param userId the value for user.user_id
     *
     * @mbg.generated
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.user_name
     *
     * @return the value of user.user_name
     *
     * @mbg.generated
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.user_name
     *
     * @param userName the value for user.user_name
     *
     * @mbg.generated
     */
    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.user_paw
     *
     * @return the value of user.user_paw
     *
     * @mbg.generated
     */
    public String getUserPaw() {
        return userPaw;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.user_paw
     *
     * @param userPaw the value for user.user_paw
     *
     * @mbg.generated
     */
    public void setUserPaw(String userPaw) {
        this.userPaw = userPaw == null ? null : userPaw.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.unionid
     *
     * @return the value of user.unionid
     *
     * @mbg.generated
     */
    public String getUnionid() {
        return unionid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.unionid
     *
     * @param unionid the value for user.unionid
     *
     * @mbg.generated
     */
    public void setUnionid(String unionid) {
        this.unionid = unionid == null ? null : unionid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.org
     *
     * @return the value of user.org
     *
     * @mbg.generated
     */
    public String getOrg() {
        return org;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.org
     *
     * @param org the value for user.org
     *
     * @mbg.generated
     */
    public void setOrg(String org) {
        this.org = org == null ? null : org.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.last_org
     *
     * @return the value of user.last_org
     *
     * @mbg.generated
     */
    public String getLastOrg() {
        return lastOrg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.last_org
     *
     * @param lastOrg the value for user.last_org
     *
     * @mbg.generated
     */
    public void setLastOrg(String lastOrg) {
        this.lastOrg = lastOrg == null ? null : lastOrg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.isManager
     *
     * @return the value of user.isManager
     *
     * @mbg.generated
     */
    public String getIsmanager() {
        return ismanager;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.isManager
     *
     * @param ismanager the value for user.isManager
     *
     * @mbg.generated
     */
    public void setIsmanager(String ismanager) {
        this.ismanager = ismanager == null ? null : ismanager.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.isRegister
     *
     * @return the value of user.isRegister
     *
     * @mbg.generated
     */
    public String getIsregister() {
        return isregister;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.isRegister
     *
     * @param isregister the value for user.isRegister
     *
     * @mbg.generated
     */
    public void setIsregister(String isregister) {
        this.isregister = isregister == null ? null : isregister.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.register_number
     *
     * @return the value of user.register_number
     *
     * @mbg.generated
     */
    public String getRegisterNumber() {
        return registerNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.register_number
     *
     * @param registerNumber the value for user.register_number
     *
     * @mbg.generated
     */
    public void setRegisterNumber(String registerNumber) {
        this.registerNumber = registerNumber == null ? null : registerNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.register_time
     *
     * @return the value of user.register_time
     *
     * @mbg.generated
     */
    public String getRegisterTime() {
        return registerTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.register_time
     *
     * @param registerTime the value for user.register_time
     *
     * @mbg.generated
     */
    public void setRegisterTime(String registerTime) {
        this.registerTime = registerTime == null ? null : registerTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.create_time
     *
     * @return the value of user.create_time
     *
     * @mbg.generated
     */
    public String getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.create_time
     *
     * @param createTime the value for user.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(String createTime) {
        this.createTime = createTime == null ? null : createTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.update_time
     *
     * @return the value of user.update_time
     *
     * @mbg.generated
     */
    public String getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.update_time
     *
     * @param updateTime the value for user.update_time
     *
     * @mbg.generated
     */
    public void setUpdateTime(String updateTime) {
        this.updateTime = updateTime == null ? null : updateTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        User other = (User) that;
        return (this.getUserId() == null ? other.getUserId() == null : this.getUserId().equals(other.getUserId()))
            && (this.getUserName() == null ? other.getUserName() == null : this.getUserName().equals(other.getUserName()))
            && (this.getUserPaw() == null ? other.getUserPaw() == null : this.getUserPaw().equals(other.getUserPaw()))
            && (this.getUnionid() == null ? other.getUnionid() == null : this.getUnionid().equals(other.getUnionid()))
            && (this.getOrg() == null ? other.getOrg() == null : this.getOrg().equals(other.getOrg()))
            && (this.getLastOrg() == null ? other.getLastOrg() == null : this.getLastOrg().equals(other.getLastOrg()))
            && (this.getIsmanager() == null ? other.getIsmanager() == null : this.getIsmanager().equals(other.getIsmanager()))
            && (this.getIsregister() == null ? other.getIsregister() == null : this.getIsregister().equals(other.getIsregister()))
            && (this.getRegisterNumber() == null ? other.getRegisterNumber() == null : this.getRegisterNumber().equals(other.getRegisterNumber()))
            && (this.getRegisterTime() == null ? other.getRegisterTime() == null : this.getRegisterTime().equals(other.getRegisterTime()))
            && (this.getCreateTime() == null ? other.getCreateTime() == null : this.getCreateTime().equals(other.getCreateTime()))
            && (this.getUpdateTime() == null ? other.getUpdateTime() == null : this.getUpdateTime().equals(other.getUpdateTime()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getUserId() == null) ? 0 : getUserId().hashCode());
        result = prime * result + ((getUserName() == null) ? 0 : getUserName().hashCode());
        result = prime * result + ((getUserPaw() == null) ? 0 : getUserPaw().hashCode());
        result = prime * result + ((getUnionid() == null) ? 0 : getUnionid().hashCode());
        result = prime * result + ((getOrg() == null) ? 0 : getOrg().hashCode());
        result = prime * result + ((getLastOrg() == null) ? 0 : getLastOrg().hashCode());
        result = prime * result + ((getIsmanager() == null) ? 0 : getIsmanager().hashCode());
        result = prime * result + ((getIsregister() == null) ? 0 : getIsregister().hashCode());
        result = prime * result + ((getRegisterNumber() == null) ? 0 : getRegisterNumber().hashCode());
        result = prime * result + ((getRegisterTime() == null) ? 0 : getRegisterTime().hashCode());
        result = prime * result + ((getCreateTime() == null) ? 0 : getCreateTime().hashCode());
        result = prime * result + ((getUpdateTime() == null) ? 0 : getUpdateTime().hashCode());
        return result;
    }

	@Override
	public String toString() {
		return "User [userId=" + userId + ", userName=" + userName
				+ ", userPaw=" + userPaw + ", unionid=" + unionid + ", org="
				+ org + ", lastOrg=" + lastOrg + ", ismanager=" + ismanager
				+ ", isregister=" + isregister + ", registerNumber="
				+ registerNumber + ", registerTime=" + registerTime
				+ ", createTime=" + createTime + ", updateTime=" + updateTime
				+ "]";
	}

   
}