package springboot.model;

import java.io.Serializable;

public class ProductMaintain implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_maintain.product_id
     *
     * @mbg.generated
     */
    private String productId;
    
    private String userId;

    public String getUserId() {
		return userId;
	}

	public void setUserId(String userId) {
		this.userId = userId;
	}

	/**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_maintain.activate_time
     *
     * @mbg.generated
     */
    private String activateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_maintain.org_id
     *
     * @mbg.generated
     */
    private String orgId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_maintain.isover_time
     *
     * @mbg.generated
     */
    private String isoverTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_maintain.activate_image_url
     *
     * @mbg.generated
     */
    private String activateImageUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_maintain.create_time
     *
     * @mbg.generated
     */
    private String createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_maintain.update_time
     *
     * @mbg.generated
     */
    private String updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table product_maintain
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_maintain.product_id
     *
     * @return the value of product_maintain.product_id
     *
     * @mbg.generated
     */
    public String getProductId() {
        return productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_maintain.product_id
     *
     * @param productId the value for product_maintain.product_id
     *
     * @mbg.generated
     */
    public void setProductId(String productId) {
        this.productId = productId == null ? null : productId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_maintain.activate_time
     *
     * @return the value of product_maintain.activate_time
     *
     * @mbg.generated
     */
    public String getActivateTime() {
        return activateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_maintain.activate_time
     *
     * @param activateTime the value for product_maintain.activate_time
     *
     * @mbg.generated
     */
    public void setActivateTime(String activateTime) {
        this.activateTime = activateTime == null ? null : activateTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_maintain.org_id
     *
     * @return the value of product_maintain.org_id
     *
     * @mbg.generated
     */
    public String getOrgId() {
        return orgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_maintain.org_id
     *
     * @param orgId the value for product_maintain.org_id
     *
     * @mbg.generated
     */
    public void setOrgId(String orgId) {
        this.orgId = orgId == null ? null : orgId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_maintain.isover_time
     *
     * @return the value of product_maintain.isover_time
     *
     * @mbg.generated
     */
    public String getIsoverTime() {
        return isoverTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_maintain.isover_time
     *
     * @param isoverTime the value for product_maintain.isover_time
     *
     * @mbg.generated
     */
    public void setIsoverTime(String isoverTime) {
        this.isoverTime = isoverTime == null ? null : isoverTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_maintain.activate_image_url
     *
     * @return the value of product_maintain.activate_image_url
     *
     * @mbg.generated
     */
    public String getActivateImageUrl() {
        return activateImageUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_maintain.activate_image_url
     *
     * @param activateImageUrl the value for product_maintain.activate_image_url
     *
     * @mbg.generated
     */
    public void setActivateImageUrl(String activateImageUrl) {
        this.activateImageUrl = activateImageUrl == null ? null : activateImageUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_maintain.create_time
     *
     * @return the value of product_maintain.create_time
     *
     * @mbg.generated
     */
    public String getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_maintain.create_time
     *
     * @param createTime the value for product_maintain.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(String createTime) {
        this.createTime = createTime == null ? null : createTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_maintain.update_time
     *
     * @return the value of product_maintain.update_time
     *
     * @mbg.generated
     */
    public String getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_maintain.update_time
     *
     * @param updateTime the value for product_maintain.update_time
     *
     * @mbg.generated
     */
    public void setUpdateTime(String updateTime) {
        this.updateTime = updateTime == null ? null : updateTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_maintain
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        ProductMaintain other = (ProductMaintain) that;
        return (this.getProductId() == null ? other.getProductId() == null : this.getProductId().equals(other.getProductId()))
            && (this.getActivateTime() == null ? other.getActivateTime() == null : this.getActivateTime().equals(other.getActivateTime()))
            && (this.getOrgId() == null ? other.getOrgId() == null : this.getOrgId().equals(other.getOrgId()))
            && (this.getIsoverTime() == null ? other.getIsoverTime() == null : this.getIsoverTime().equals(other.getIsoverTime()))
            && (this.getActivateImageUrl() == null ? other.getActivateImageUrl() == null : this.getActivateImageUrl().equals(other.getActivateImageUrl()))
            && (this.getCreateTime() == null ? other.getCreateTime() == null : this.getCreateTime().equals(other.getCreateTime()))
            && (this.getUpdateTime() == null ? other.getUpdateTime() == null : this.getUpdateTime().equals(other.getUpdateTime()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_maintain
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getProductId() == null) ? 0 : getProductId().hashCode());
        result = prime * result + ((getActivateTime() == null) ? 0 : getActivateTime().hashCode());
        result = prime * result + ((getOrgId() == null) ? 0 : getOrgId().hashCode());
        result = prime * result + ((getIsoverTime() == null) ? 0 : getIsoverTime().hashCode());
        result = prime * result + ((getActivateImageUrl() == null) ? 0 : getActivateImageUrl().hashCode());
        result = prime * result + ((getCreateTime() == null) ? 0 : getCreateTime().hashCode());
        result = prime * result + ((getUpdateTime() == null) ? 0 : getUpdateTime().hashCode());
        return result;
    }

	@Override
	public String toString() {
		return "ProductMaintain [productId=" + productId + ", activateTime="
				+ activateTime + ", orgId=" + orgId + ", isoverTime="
				+ isoverTime + ", activateImageUrl=" + activateImageUrl
				+ ", createTime=" + createTime + ", updateTime=" + updateTime
				+ "]";
	}

    
}